spring:
  profile: container
  datasource:
    url: jdbc:mysql://localhost:3306/iihtdb?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: pass@word1
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
server.port: 9000